import { Language } from '../types';

// 40 Most Spoken Languages Worldwide
export const languages: Language[] = [
  { code: 'en-US', name: 'English', native: 'English', flag: '🇺🇸' },
  { code: 'zh-CN', name: 'Chinese (Mandarin)', native: '中文', flag: '🇨🇳' },
  { code: 'hi-IN', name: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' },
  { code: 'es-ES', name: 'Spanish', native: 'Español', flag: '🇪🇸' },
  { code: 'fr-FR', name: 'French', native: 'Français', flag: '🇫🇷' },
  { code: 'ar-SA', name: 'Arabic', native: 'العربية', flag: '🇸🇦' },
  { code: 'bn-BD', name: 'Bengali', native: 'বাংলা', flag: '🇧🇩' },
  { code: 'ru-RU', name: 'Russian', native: 'Русский', flag: '🇷🇺' },
  { code: 'pt-PT', name: 'Portuguese', native: 'Português', flag: '🇵🇹' },
  { code: 'id-ID', name: 'Indonesian', native: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'ur-PK', name: 'Urdu', native: 'اردو', flag: '🇵🇰' },
  { code: 'de-DE', name: 'German', native: 'Deutsch', flag: '🇩🇪' },
  { code: 'ja-JP', name: 'Japanese', native: '日本語', flag: '🇯🇵' },
  { code: 'sw-KE', name: 'Swahili', native: 'Kiswahili', flag: '🇰🇪' },
  { code: 'mr-IN', name: 'Marathi', native: 'मराठी', flag: '🇮🇳' },
  { code: 'te-IN', name: 'Telugu', native: 'తెలుగు', flag: '🇮🇳' },
  { code: 'tr-TR', name: 'Turkish', native: 'Türkçe', flag: '🇹🇷' },
  { code: 'ta-IN', name: 'Tamil', native: 'தமிழ்', flag: '🇮🇳' },
  { code: 'vi-VN', name: 'Vietnamese', native: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'ko-KR', name: 'Korean', native: '한국어', flag: '🇰🇷' },
  { code: 'it-IT', name: 'Italian', native: 'Italiano', flag: '🇮🇹' },
  { code: 'th-TH', name: 'Thai', native: 'ไทย', flag: '🇹🇭' },
  { code: 'gu-IN', name: 'Gujarati', native: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'pl-PL', name: 'Polish', native: 'Polski', flag: '🇵🇱' },
  { code: 'uk-UA', name: 'Ukrainian', native: 'Українська', flag: '🇺🇦' },
  { code: 'my-MM', name: 'Burmese', native: 'မြန်မာ', flag: '🇲🇲' },
  { code: 'ml-IN', name: 'Malayalam', native: 'മലയാളം', flag: '🇮🇳' },
  { code: 'kn-IN', name: 'Kannada', native: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'or-IN', name: 'Odia', native: 'ଓଡ଼ିଆ', flag: '🇮🇳' },
  { code: 'pa-IN', name: 'Punjabi', native: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'ro-RO', name: 'Romanian', native: 'Română', flag: '🇷🇴' },
  { code: 'nl-NL', name: 'Dutch', native: 'Nederlands', flag: '🇳🇱' },
  { code: 'hu-HU', name: 'Hungarian', native: 'Magyar', flag: '🇭🇺' },
  { code: 'cs-CZ', name: 'Czech', native: 'Čeština', flag: '🇨🇿' },
  { code: 'el-GR', name: 'Greek', native: 'Ελληνικά', flag: '🇬🇷' },
  { code: 'he-IL', name: 'Hebrew', native: 'עברית', flag: '🇮🇱' },
  { code: 'fi-FI', name: 'Finnish', native: 'Suomi', flag: '🇫🇮' },
  { code: 'sv-SE', name: 'Swedish', native: 'Svenska', flag: '🇸🇪' },
  { code: 'no-NO', name: 'Norwegian', native: 'Norsk', flag: '🇳🇴' },
  { code: 'da-DK', name: 'Danish', native: 'Dansk', flag: '🇩🇰' },
];